FROM bitfusionio/flex-cuda:9.0-devel-ubuntu16.04

RUN \
  apt-get update &&\
  apt-get install -y python3 python3-pip &&\
  apt-get clean &&\
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&\
  mkdir -p /examples

WORKDIR /examples
COPY . /examples

RUN pip3 install --upgrade tensorflow_gpu numpy
